package com.fannie.service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.fannie.beans.Message;

public class MessageService {
	// this is substitute for DB connection as of now 
	Map<Integer, Message> messageMap = new HashMap<Integer, Message>();
	
	public MessageService(){
		System.out.println("Contructor for Message Service Invoked... ");
		
		Message m1 = new Message(101, "Hello Welcome to Web Service", "Simran");
		Message m2 = new Message(102, "Its good wether today.. ", "Jasmine");
		
		messageMap.put(101, m1);
		messageMap.put(102, m2);
	}

	// will have CRUD operation methods 
	
	public Message addMessage(Message message){
		// we dont check we only put assuming that we dont take the 
		// id and it will be generated by inc by 1 
		
		messageMap.put(message.getMessageId(), message);
		return message;
	}
	
	// to get the message 
	public Message getMessage(int messageId){
		return messageMap.get(messageId);
	}
	
	// to get all the message in the map, only values of the map is returned 
	public List<Message> getAllMessages(){
		return new ArrayList<Message>(messageMap.values());
	}
	
	public Message updateMessage(Message message){
		messageMap.put(message.getMessageId(), message);
		return message;
	}
	
	public String deleteMessage(int messageId){
		if(this.getMessage(messageId) !=  null){
			messageMap.remove(messageId);
			return "Found And Deleted -" + messageId;
		}
		return "Sorry Message with Id " + messageId +" is not found";
	}
}
